# -*- coding: utf-8 -*-
"""SentimentAnalysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EYYChwUmx3figBHp8GwrwDpQhWx7dv8K
"""

#import the libraries
import pandas as pd
from textblob import TextBlob
import matplotlib.pyplot as plt

# Load the data
from google.colab import files
uploaded = files.upload()

# Get the data
df = pd.read_csv('zomato_reviews.csv')

def get_sentiment(review_text):
    """
    Performs sentiment analysis on a review text using TextBlob.
    Returns the sentiment polarity score and sentiment class.
    """
    blob = TextBlob(str(review_text))
    sentiment_score = blob.sentiment.polarity
    
    if sentiment_score > 0:
        sentiment_class = 'Positive'
    elif sentiment_score < 0:
        sentiment_class = 'Negative'
    else:
        sentiment_class = 'Neutral'
    
    return sentiment_score, sentiment_class

# Apply sentiment analysis function to reviews
df['Sentiment_Score'], df['Sentiment_Class'] = zip(*df['review'].apply(get_sentiment))

# Handle missing values
df.dropna(subset=['review'], inplace=True)

# Print dataset with sentiment class and score
print(df)

# Create histogram of sentiment scores
plt.hist(df['Sentiment_Score'], bins='auto')
plt.xlabel('Sentiment Score')
plt.ylabel('Number of Reviews')
plt.title('Distribution of Sentiment Scores')
plt.show()